### ISSUE TITLE
New Block Version

### ISSUE THREAD

**Issue by TheAxZim** [ladimolnar/BitcoinDatabaseGenerator#5] opened 2016-02-29 02:29 UTC
Block Version 805306368 recently released. Once the parser hits blk00443.dat it will fail around half way through and the entire process will end. DLL needs to be updated to handle the new block version.

**Comment by ladimolnar** [comment] 2016-03-05 03:43
Thank you TheAxZim. The issue is now fixed with v 1.5

**Closed as completed by ladimolnar** 2016-03-05 03:43 UTC
